name       : vifm
version    : 0.10.1
release    : 5
source     :
    - https://github.com/vifm/vifm/archive/v0.10.1.tar.gz : f5e6add7b0c8221fc5eb5b60c7ea483a141769afea2167f1535d66785bb654ec
homepage   : https://vifm.info/
license    : GPL-2.0-or-later
component  : system.utils
summary    : ncurses file manager with vi keybindings
description: |
    Vifm is a file manager with curses interface, which provides Vi[m]-like environment for managing objects within file systems, extended with some useful ideas from mutt. If you use vi, Vifm gives you complete keyboard control over your files without having to learn a new set of commands.
builddeps  :
    - man-db
setup      : |
    %patch -p1 < $pkgfiles/fic-color-scheme-of-other-panel.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
