name       : vifm
version    : '0.13'
release    : 11
source     :
    - https://github.com/vifm/vifm/archive/refs/tags/v0.13.tar.gz : 8379397b2824cc74a91f5cfa00b5496f5d08cdcec18e3d13b64c480151225ca8
homepage   : https://vifm.info/
license    : GPL-2.0-or-later
component  : system.utils
summary    : ncurses file manager with vi keybindings
description: |
    Vifm is a file manager with curses interface, which provides Vi[m]-like environment for managing objects within file systems, extended with some useful ideas from mutt. If you use vi, Vifm gives you complete keyboard control over your files without having to learn a new set of commands.
builddeps  :
    - man-db
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
