name       : vifm
version    : 0.8.2
release    : 3
source     :
    - https://freefr.dl.sourceforge.net/project/vifm/vifm/vifm-0.8.2.tar.bz2 : 8b466d766658a24d07fc2039a26fefc6a018f5653684a6035183ca79f02c211f
homepage   : http://vifm.sourceforge.net
license    : GPL-2.0
summary    : ncurses file manager with vi keybindings
description: |
    Vifm is a ncurses based file manager with vi like keybindings. Vifm gives complete keyboard control over files without having to learn a new set of commands.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
