name       : vifm
version    : '0.11'
release    : 6
source     :
    - https://github.com/vifm/vifm/archive/v0.11.tar.gz : 7b76f39b2225db2960ee125da204ce6264fe992ec2d9f2954ab74ba3c28ce0ec
homepage   : https://vifm.info/
license    : GPL-2.0-or-later
component  : system.utils
summary    : ncurses file manager with vi keybindings
description: |
    Vifm is a file manager with curses interface, which provides Vi[m]-like environment for managing objects within file systems, extended with some useful ideas from mutt. If you use vi, Vifm gives you complete keyboard control over your files without having to learn a new set of commands.
builddeps  :
    - man-db
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
