name       : vifm
version    : 0.9.1
release    : 4
source     :
    - https://freefr.dl.sourceforge.net/project/vifm/vifm/vifm-0.9.1.tar.bz2 : 28b9a4b670d9ddc9af8c9804dc22fa93f4fd0adabce94d43ebedc157a5dce7b3
homepage   : http://vifm.sourceforge.net
license    : GPL-2.0-or-later
summary    : ncurses file manager with vi keybindings
description: |
    Vifm is a ncurses based file manager with vi like keybindings. Vifm gives complete keyboard control over files without having to learn a new set of commands.
builddeps  :
    - man-db
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
